
script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $(git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH | tr -d '\n')
  - CHANGED_FILES=$(git diff --name-only --diff-filter=AM $TRAVIS_COMMIT_RANGE | tr -d '\n')
  - echo $CHANGED_FILES
  - source ./check-changelog.sh $CHANGED_FILES

