language: php

script:
  - git branch
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT_RANGE
  - CHANGED_FILES=($(git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH)) && ./check-changelog.sh $CHANGED_FILES
  - echo $CHANGED_FILES
