language: php

script:
  - echo $(git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH)
  - CHANGED_FILES=($(git diff --name-only --diff-filter=M $(echo $TRAVIS_COMMIT_RANGE | sed 's/\.\.\./\ /')))
  - echo $CHANGED_FILES
  - ./check-changelog.sh $CHANGED_FILES
